package com.aniruddha81.gaalifinderv2.data.local

import androidx.room.migration.Migration
import androidx.sqlite.db.SupportSQLiteDatabase

/** v1 -> v2: added the "new clip" badge flag. */
val MIGRATION_1_2 = object : Migration(1, 2) {
    override fun migrate(db: SupportSQLiteDatabase) {
        db.execSQL("ALTER TABLE audio_files ADD COLUMN isNew INTEGER NOT NULL DEFAULT 1")
    }
}

/**
 * v2 -> v3: added duration/size/added-at, plus lookup indices.
 *
 * Existing rows get 0 for the new columns; the metadata backfill fills them in later by probing
 * the files, so the migration itself stays fast and cannot fail on a missing file.
 */
val MIGRATION_2_3 = object : Migration(2, 3) {
    override fun migrate(db: SupportSQLiteDatabase) {
        db.execSQL("ALTER TABLE audio_files ADD COLUMN durationMs INTEGER NOT NULL DEFAULT 0")
        db.execSQL("ALTER TABLE audio_files ADD COLUMN sizeBytes INTEGER NOT NULL DEFAULT 0")
        db.execSQL("ALTER TABLE audio_files ADD COLUMN addedAt INTEGER NOT NULL DEFAULT 0")
        db.execSQL("CREATE INDEX IF NOT EXISTS index_audio_files_fileName ON audio_files (fileName)")
        db.execSQL("CREATE INDEX IF NOT EXISTS index_audio_files_source ON audio_files (source)")
    }
}

/**
 * v3 -> v4: the table stops being a record of local files and becomes a cache of the shared
 * `audio_metadata` catalogue.
 *
 * The old rows cannot be carried across. Their primary key was an autogenerated row id with no
 * counterpart on the server, and a locally-imported clip has no `audio_metadata` document, no
 * `fileId` and no uploader — so there is nothing to migrate them *to*. The old table is dropped
 * and the first sync after upgrade repopulates from Appwrite.
 *
 * Files previously downloaded into `filesDir/clips` are deliberately left on disk: the clip
 * cache re-adopts a file whose name it recognises, so an upgrading user does not have to
 * re-download the catalogue they already have.
 */
val MIGRATION_3_4 = object : Migration(3, 4) {
    override fun migrate(db: SupportSQLiteDatabase) {
        db.execSQL("DROP TABLE IF EXISTS audio_files")
        db.execSQL(
            """
            CREATE TABLE IF NOT EXISTS audio_clips (
                documentId TEXT NOT NULL PRIMARY KEY,
                fileId TEXT NOT NULL,
                fileName TEXT NOT NULL,
                uploaderId TEXT NOT NULL,
                uploaderName TEXT NOT NULL,
                isNew INTEGER NOT NULL,
                durationMs INTEGER NOT NULL DEFAULT 0,
                sizeBytes INTEGER NOT NULL DEFAULT 0,
                createdAt INTEGER NOT NULL DEFAULT 0,
                likeCount INTEGER NOT NULL DEFAULT 0,
                dislikeCount INTEGER NOT NULL DEFAULT 0,
                myReaction TEXT,
                cachedPath TEXT
            )
            """.trimIndent()
        )
        db.execSQL("CREATE INDEX IF NOT EXISTS index_audio_clips_fileName ON audio_clips (fileName)")
        db.execSQL("CREATE INDEX IF NOT EXISTS index_audio_clips_uploaderId ON audio_clips (uploaderId)")
        db.execSQL("CREATE INDEX IF NOT EXISTS index_audio_clips_createdAt ON audio_clips (createdAt)")
    }
}

val ALL_MIGRATIONS = arrayOf(MIGRATION_1_2, MIGRATION_2_3, MIGRATION_3_4)
